name: Update iOS Dependency

on:
  repository_dispatch:
    types: [update-ios-dependency]
  workflow_dispatch:
    inputs:
      version:
        description: 'iOS SDK version to update to'
        required: true
        type: string

jobs:
  update-ios-dependency:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update podspec
        run: |
          # Update the iOS SDK dependency version in the podspec
          sed -i "s/s\.dependency 'Helium', '[^']*'/s.dependency 'Helium', '${{ github.event.client_payload.version || github.event.inputs.version }}'/g" PaywallSdkReactNative.podspec

      - name: Bump package.json version
        run: |
          # Get current version and increment patch version
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          NEW_VERSION=$(node -e "
            const current = '$CURRENT_VERSION';
            const parts = current.split('.');
            const major = parseInt(parts[0]);
            const minor = parseInt(parts[1]);
            const patch = parseInt(parts[2]) + 1;
            console.log(\`\${major}.\${minor}.\${patch}\`);
          ")

          # Update package.json with new version
          sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$NEW_VERSION\"/g" package.json

          echo "Bumped version from $CURRENT_VERSION to $NEW_VERSION"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Update helium-swift SDK dependency to ${{ github.event.client_payload.version || github.event.inputs.version }}"
          branch: update-ios-sdk-${{ github.event.client_payload.version || github.event.inputs.version }}
          title: "Update helium-swift SDK to ${{ github.event.client_payload.version || github.event.inputs.version }}"
          body: |
            Automated update of helium-swift SDK dependency to version ${{ github.event.client_payload.version || github.event.inputs.version }}.

            Changes:
            - Updated podspec dependency version
            - Bumped package.json version (patch increment)

            This PR was automatically created by the iOS SDK release workflow.
